apiVersion: v1
kind: Service
metadata:
  name: go-application-service
spec:
  selector:
    app: go-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  